[package]
name = "roachrs"
version = "0.1.0"
authors = ["Tobias Schottdorf <tobias.schottdorf@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "*"
rocksdb = "0.6"
bio = "*"
hlc = "*"
